# Generated by Django 6.0.3 on 2026-03-08 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100, verbose_name='Категория выполнения')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique_for_date='created_at', verbose_name='Название задачи')),
                ('description', models.TextField(max_length=100, verbose_name='Описание задачи')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('pending', 'Pending'), ('blocked', 'Blocked'), ('done', 'Done')], default='new', max_length=20, verbose_name='Статус задачи')),
                ('deadline', models.DateTimeField(help_text='Дата и время дедлайн')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания')),
                ('categories', models.ManyToManyField(related_name='tasks', to='my_new_app.category', verbose_name='Категории задачи')),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique_for_date='created_at', verbose_name='Название подзадачи')),
                ('description', models.TextField(max_length=100, verbose_name='Описание подзадачи')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('pending', 'Pending'), ('blocked', 'Blocked'), ('done', 'Done')], default='new', max_length=20, verbose_name='Статус задачи')),
                ('deadline', models.DateTimeField(help_text='Дата и время дедлайн')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания')),
                ('task', models.ForeignKey(help_text='Основная задача', on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='my_new_app.task')),
            ],
        ),
    ]
