# Generated by Django 6.0.3 on 2026-04-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_new_app', '0004_task_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Название пользователя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email пользователя')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль пользователя')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'task_manager_user',
            },
        ),
    ]
